/**
 * ============================================================================
 * Prométhée — Assistant IA avancé
 * ============================================================================
 * Auteur  : Pierre COUGET ktulu.analog@gmail.com
 * Licence : GNU Affero General Public License v3.0 (AGPL-3.0)
 *           https://www.gnu.org/licenses/agpl-3.0.html
 * Année   : 2026
 * ----------------------------------------------------------------------------
 * Ce fichier fait partie du projet Prométhée.
 * Vous pouvez le redistribuer et/ou le modifier selon les termes de la
 * licence AGPL-3.0 publiée par la Free Software Foundation.
 * ============================================================================
 *
 *
 */

import React from "react";

export const s: Record<string, React.CSSProperties> = {
  // ── Sidebar fermée (rail étroit 48px) ─────────────────────────────────
  sidebarClosed: {
    width: 48,
    minWidth: 48,
    maxWidth: 48,
    background: "var(--sidebar-bg)",
    borderRight: "1px solid var(--sidebar-border)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: 8,
    paddingBottom: 10,
    gap: 2,
    height: "100%",
    flexShrink: 0,
    zIndex: 20,
    position: "relative",
    overflow: "hidden",
  },

  // ── Sidebar ouverte (colonne 240px) ────────────────────────────────────
  sidebarOpen: {
    width: 240,
    minWidth: 240,
    maxWidth: 240,
    background: "var(--sidebar-bg)",
    borderRight: "1px solid var(--sidebar-border)",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    paddingTop: 0,
    paddingBottom: 0,
    height: "100%",
    flexShrink: 0,
    zIndex: 20,
    position: "relative",
    overflow: "hidden",
  },

  sidebarHeaderClosed: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
    paddingTop: 2,
    paddingBottom: 4,
    width: "100%",
  },

  sidebarHeaderOpen: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 10px 8px 12px",
    borderBottom: "1px solid var(--sidebar-border)",
    flexShrink: 0,
  },

  appLogoWrap: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    overflow: "hidden",
  },
  appLogoIcon: {
    width: 30,
    height: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    background: "var(--accent)",
    flexShrink: 0,
  },
  appLogoLetter: {
    fontSize: 16,
    fontWeight: 700,
    color: "#fff",
    lineHeight: 1,
    letterSpacing: "-0.02em",
    fontFamily: "Georgia, 'Times New Roman', serif",
  },
  appName: {
    fontSize: 15,
    fontWeight: 700,
    color: "var(--text-primary)",
    letterSpacing: "-0.01em",
    whiteSpace: "nowrap" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },

  modelChipWrap: {
    padding: "4px 12px 2px",
    flexShrink: 0,
  },

  sidebarBottom: {
    borderTop: "1px solid var(--sidebar-border)",
    flexShrink: 0,
    padding: "4px 4px",
  },
  sidebarBottomRow: {
    display: "flex",
    alignItems: "center",
    gap: 0,
  },

  railBtn: {
    width: 34,
    height: 34,
    border: "none",
    background: "none",
    cursor: "pointer",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-muted)",
    transition: "background 0.12s",
    flexShrink: 0,
  },
  railSep: {
    width: 24,
    height: 1,
    background: "var(--sidebar-border)",
    margin: "4px 0",
    flexShrink: 0,
  },
  recentConvsList: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: 4,
    width: "100%",
    padding: "2px 0",
    overflowY: "auto" as const,
    overflowX: "hidden" as const,
    flexShrink: 1,
  },
  navItems: {
    display: "flex",
    flexDirection: "column" as const,
    padding: "4px 8px",
    gap: 1,
    flexShrink: 0,
  },
  navSep: {
    height: 1,
    background: "var(--sidebar-border)",
    margin: "6px 12px",
    flexShrink: 0,
  },
  activeFolderHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "2px 14px 4px",
    flexShrink: 0,
  },
  activeFolderBack: {
    background: "none",
    border: "none",
    color: "var(--text-muted)",
    cursor: "pointer",
    fontSize: 14,
    padding: "0 2px",
    lineHeight: 1,
    flexShrink: 0,
  },
  activeFolderName: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--accent)",
    letterSpacing: "0.04em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    flex: 1,
  },
  recentsLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.04em",
    padding: "2px 14px 4px",
    flexShrink: 0,
    userSelect: "none" as const,
  },

  // ── Modale centrée ────────────────────────────────────────────────────
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0, 0, 0, 0.25)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 400,
    backdropFilter: "blur(2px)",
  },
  modalBox: {
    width: 340,
    maxHeight: "88vh",
    background: "var(--surface-bg)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    boxShadow: "0 8px 40px rgba(0,0,0,0.4)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  modalBoxWide: {
    width: "min(860px, 92vw)",
    maxHeight: "90vh",
  },
  modalBoxDiscussions: {
    width: "min(600px, 92vw)",
    maxHeight: "85vh",
  },
  modalBoxTools: {
    width: "min(780px, 92vw)",
    height: "88vh",
    maxHeight: "88vh",
  },
  modalBoxVfs: {
    width: "min(720px, 92vw)",
    height: "85vh",
    maxHeight: "85vh",
  },
  modalBoxIngest: {
    width: "min(600px, 92vw)",
    height: "85vh",
    maxHeight: "85vh",
  },
  panelHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 14px 8px",
    borderBottom: "1px solid var(--sidebar-border)",
    flexShrink: 0,
  },
  panelTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-secondary)",
    letterSpacing: "0.01em",
  },
  panelClose: {
    background: "none",
    border: "none",
    color: "var(--text-muted)",
    cursor: "pointer",
    fontSize: 14,
    padding: "2px 6px",
    borderRadius: 5,
    lineHeight: 1,
  },
  projCreateBtn: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "4px 10px",
    color: "var(--accent)",
    fontSize: 12,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  projItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    border: "none",
    borderRadius: 8,
    padding: "8px 10px",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 13,
    textAlign: "left" as const,
    transition: "background 0.12s",
  },
  projItemIcon: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
  },
  projItemName: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  modelChip: {
    fontSize: 10,
    color: "var(--text-muted)",
    background: "var(--elevated-bg)",
    border: "1px solid var(--border)",
    borderRadius: 4,
    padding: "2px 6px",
    maxWidth: 110,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },

  // ── Actions dans le panneau ────────────────────────────────────────────
  newChatBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    margin: "10px 10px 4px",
    padding: "7px 12px",
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 7,
    color: "var(--text-primary)",
    fontSize: 13,
    cursor: "pointer",
    fontWeight: 500,
    flexShrink: 0,
  },
  searchWrap: {
    padding: "4px 10px 6px",
    flexShrink: 0,
  },
  searchInput: {
    width: "100%",
    padding: "5px 10px",
    background: "var(--input-bg)",
    border: "1px solid var(--input-border)",
    borderRadius: 6,
    color: "var(--input-color)",
    fontSize: 13,
    outline: "none",
    boxSizing: "border-box",
  },

  // ── Arbre ─────────────────────────────────────────────────────────────
  tree: {
    flex: 1,
    overflowY: "auto",
    overflowX: "hidden",
    padding: "0 0 8px",
  },
  folderRow: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    cursor: "pointer",
    userSelect: "none",
    color: "var(--sidebar-folder-color)",
    fontSize: 13,
    borderRadius: 4,
    margin: "0 4px",
    transition: "background 0.1s",
  },
  folderChildren: { paddingLeft: 0 },
  folderName: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  arrow: {
    width: 12,
    display: "flex",
    alignItems: "center",
    flexShrink: 0,
  },
  convRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 10px",
    paddingLeft: 22,
    cursor: "pointer",
    fontSize: 13,
    borderRadius: 4,
    margin: "0 4px",
    transition: "background 0.1s",
    userSelect: "none",
  },
  convTitle: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  emptyHint: {
    fontSize: 11,
    color: "var(--text-disabled)",
    padding: "4px 28px",
    fontStyle: "italic",
  },
  hint: {
    padding: "12px 12px",
    color: "var(--text-muted)",
    fontSize: 12,
  },
  inlineInput: {
    flex: 1,
    background: "var(--input-bg)",
    border: "1px solid var(--accent)",
    borderRadius: 3,
    color: "var(--input-color)",
    fontSize: 13,
    padding: "0 4px",
    outline: "none",
  },

  // ── Drag overlay ──────────────────────────────────────────────────────
  dragOverlay: {
    display: "flex",
    alignItems: "center",
    background: "var(--elevated-bg)",
    border: "1px solid var(--accent)",
    borderRadius: 6,
    padding: "5px 10px",
    fontSize: 13,
    color: "var(--text-primary)",
    boxShadow: "0 4px 16px rgba(0,0,0,0.3)",
    pointerEvents: "none",
  },

  // ── Menu ··· par ligne ──────────────────────────────────────────────
  menuDotBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "var(--text-muted)",
    fontSize: 15,
    padding: "2px 5px",
    borderRadius: 4,
    lineHeight: 1,
    flexShrink: 0,
    opacity: 1,
    transition: "background 0.1s",
  },
  convBubbleMenu: {
    position: "absolute" as const,
    right: 0,
    top: "100%",
    zIndex: 9999,
    background: "var(--menu-bg)",
    border: "1px solid var(--menu-border)",
    borderRadius: 8,
    boxShadow: "0 6px 24px rgba(0,0,0,0.3)",
    minWidth: 180,
    padding: "3px 0",
  },
  ctxSep: {
    height: 1,
    background: "var(--border)",
    margin: "3px 0",
  },
  bubbleItem: {
    display: "block" as const,
    width: "100%",
    background: "none",
    border: "none",
    padding: "7px 14px",
    textAlign: "left" as const,
    cursor: "pointer",
    fontSize: 13,
    color: "var(--menu-color, var(--text-primary))",
    fontFamily: "inherit",
    whiteSpace: "nowrap" as const,
  },
  submenu: {
    position: "absolute" as const,
    left: "100%",
    top: 0,
    background: "var(--menu-bg)",
    border: "1px solid var(--menu-border)",
    borderRadius: 8,
    boxShadow: "0 4px 16px rgba(0,0,0,0.2)",
    minWidth: 160,
    padding: "3px 0",
    zIndex: 10000,
  },
  inlineSubmenu: {
    borderTop: "1px solid var(--border)",
    borderBottom: "1px solid var(--border)",
    background: "var(--elevated-bg, rgba(0,0,0,0.03))",
    margin: "2px 0",
  },
  submenuItem: {
    display: "block" as const,
    width: "100%",
    background: "none",
    border: "none",
    padding: "6px 14px 6px 24px",
    textAlign: "left" as const,
    cursor: "pointer",
    fontSize: 12,
    color: "var(--menu-color, var(--text-primary))",
    fontFamily: "inherit",
    whiteSpace: "nowrap" as const,
  },
};
